apiVersion: v1
kind: Service
metadata:
  name: gandalf-service
  labels:
    app: gandalf-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
spec:
  selector:
    app: gandalf-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
